- name: update yum
  shell: yum -y update

- name: configure swapfile for memory
  shell: |
    fallocate -l 2G /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile

- name: copy files
  copy:
    src: "{{item.key}}"
    dest: "{{item.value.dest}}"
    mode: "{{item.value.mode}}"
    backup: "{{item.value.backup}}"
  with_dict:
    - "{{ copy_files }}"
